# Generated by Django 2.1 on 2021-03-03 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spam_filtering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, max_length=1000)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 3, 3, 8, 7, 35, 509216), null=True)),
            ],
        ),
    ]
