# Generated by Django 2.1 on 2021-03-04 06:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spam', '0002_auto_20210304_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spam_filtering',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listings.Listing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spam_filtering',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 6, 2, 27, 273367)),
        ),
        migrations.AlterField(
            model_name='spam_filtering',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
